### ISSUE TITLE
regions file error if fasta not sorted

### ISSUE THREAD

**Issue by tvkent** [ANGSD/angsd#11]
Regions files don't work unless chromosome headers in fasta references and/or ancestral references are in numerical order.  As most fastas don't come in numerical order and there's no one quick sort function to alleviate this, can this be fixed in angsd? Or at least mentioned in the documentation?

**Comment by ANGSD** [comment]
The only requirement for the region files (the -rf files) are that they are grouped by first column.
There shouldn't be any subtle assumptions about the ordering otherwise or any dependency with the sorting of the fastas or the bams.

The -rf files can be sorted like:
sort -k1 input.rf >output.rf
There is some information about the -sites filter here:
http://www.popgen.dk/angsd/index.php/Sites

Don't hesitate to get back to me if you have an test example that doesn't work as expected

Best

**Comment by ANGSD** [comment]
I'm closing this issue. Feel free to reopen.
