### ISSUE TITLE
Segmentation fault problem

### ISSUE THREAD

**Issue by dmvelasco** [ANGSD/angsd#13]
I am trying to run 32 samples with the following commands
```
./angsd -bam angsd.persicabam.txt -anc PC01.fa -ref Prunus_persica_v1.0_scaffolds.fa -nInd 32 -doMajorMinor 1 -doMaf 1 -doSaf 2 -GL 1 -doPost 1 -doGeno 32 -indF PP_r.indF -nThreads 4 -nQueueSize 20 -minMapQ 30 -minQ 20 -r scaffold_8: -out PP_s8 
```
in ` angsd version: 0.900-3-g100443c (htslib: 1.2.1-71-g30fb9ee) build(May 14 2015 10:16:45)`, but end up with the following error
```
        -> Done reading data waiting for calculations to finish
        -> Done waiting for threads
/var/spool/slurmd/job3693807/slurm_script: line 59: 14620 Segmentation fault      (core dumped) 
```
(line 59 contains the above angsd commands).

Output files that appear to be of expected size are .arg, .geno.gz, .mafs.gz, .saf.gz, and .saf.pos.gz. The .saf.idx file is of size zero bytes. When I run the same commands with a different group of only 14 samples (with or without `-nQueueSize`) this problem does not occur. (It also did not occur in the previous version of ANGSD.)

Grateful for any thoughts or suggestions you may have.

**Comment by ANGSD** [comment]
The -doSaf was moved to a more intelligent container format in the latests version. Maybe a bug managed to sneak in. I can see that it crashes when it tries to close the files. 

Is it a big scaffold? Would it take long to reproduce the segfault? I Just pushed a new version to github could you try rerun with that?

**Comment by dmvelasco** [comment]
Excellent! I'll give it a try. It is a tiny genome, comparatively, at ~230 Mb with the first chromosome being the largest at ~48 Mb. While I didn't time it exactly, it was around an hour to finish. I will let you know how it goes. Thanks for your help!

**Comment by dmvelasco** [comment]
Seems to have worked, a non-empty .saf.idx was produced and no segfault.
Thanks again for your help!

**Comment by SIlviaHinojosa** [comment]
Hello
I am having the same problem : Parsing 7 number of samples 
Segmentation fault (core dumped) . I am using the latest angsd version and tried diferent -nThreads 1,10,20 etc  ... here is the comand line.
 /angsd -out /user/shinojosa/bams/Dysdera_all/banda_all_out -nThreads 1 -doGlf 2  -doMajorMinor 1 -GL 1 -P 5 -doMaf 2 -SNP_pval 2e-6 -checkBamHeaders 0 -bam /user/shinojosa/bams/Dysdera_all/bam_banda.filelist

Thanks!

**Comment by ANGSD** [comment]
It seems to work for my bamfiles:

[fvr124@a00643 angsd]$ ./angsd -nThreads 1 -doglf 2 -doMajorMinor 1 -GL 1
-P 5 -doMaf 2 -SNP_pval 2e-6 -checkBamHeaders 0 -bam list  -r 1

-> angsd version: 0.917-37-g21acca9-dirty (htslib: 1.3.2-225-g8dd26ff)
build(Feb 24 2017 11:22:41)

-> No '-out' argument given, output files will be called 'angsdput'

-> SNP-filter using a pvalue: 2.000000e-06 correspond to 22.595043
likelihood units

-> Parsing 33 number of samples

-> Region lookup 1/1

-> Printing at chr: 1 pos:14086716 chunknumber 300 contains 251 sites

-> Done reading data waiting for calculations to finish

-> Done waiting for threads

-> Output filenames:

->"angsdput.arg"

->"angsdput.beagle.gz"

->"angsdput.mafs.gz"

-> Tue Mar  7 09:46:48 2017

-> Arguments and parameters for all analysis are located in .arg file

[ALL done] cpu-time used =  37.65 sec

[ALL done] walltime used =  10.00 sec


What is the difference in header, since you are using the -checkbamheaders
0?

**Comment by SIlviaHinojosa** [comment]
Hello

This are my headers of two of the samples :


@HD    VN:1.0    SO:coordinate
@SQ    SN:comp0_seq0    LN:5714

@HD    VN:1.0    SO:coordinate
@SQ    SN:comp0    LN:5219


I have tried to run it without checking bam headers and I got an error that
headers were different, then I ran it with the checkbam and worked, then I
added this two samples and It didn worked any more. I was using the program
just fine for the last couple of weeks and then this error started.

Silvia


2017-03-07 9:48 GMT+01:00 ANGSD <notifications@github.com>:

**Comment by ANGSD** [comment]
It looks like your bams dont cover the same chromosomes? If things keep
crashing then try reformatting your bams so they have identical headers.
