### ISSUE TITLE
smartCount input

### ISSUE THREAD

**Issue by inndcm** [ANGSD/angsd#137]
Hi,

I would like to use smartCount utility to obtain input to treemix but I don't understand what is the input file for the script to work.

Could you give me a hint?

Thanks!

**Comment by ANGSD** [comment]
Hello the smartcount stuff was something i played with some years ago. It is not something I've used for quite some time. Im wondering how you find this functionality since it is not on the wiki:)

Here is an example:
./angsd -i ../smallBam/smallNA06985.mapped.ILLUMINA.bwa.CEU.low_coverage.20111114.bam -docounts 1 -dosmartcounts 1 -out first
 ./angsd -i ../smallBam/smallNA06994.mapped.ILLUMINA.bwa.CEU.low_coverage.20111114.bam -docounts 1 -dosmartcounts 1 -out second
ls *.idx >flist
./misc/smartCount treemixer -bin flist >treemix.input

I would double-check the results and not trust it blindly.

**Comment by ANGSD** [comment]
Im closing this issue, feel free to reopen if needed

**Comment by Jungal10** [comment]
I am reopenning this issue for a further question. I am interested in converting the input to treemix. 
Although I have a list of more than 100 bam files.

Will the smartcount still work with `-b BAM_LIST_FILE` instead of `-i BAM_FILE`?

Thank you
