### ISSUE TITLE
Segmentation fault -doThetas

### ISSUE THREAD

**Issue by clairemerot** [ANGSD/angsd#148]
Hello,
I keep having a "segmentation fault" with the -dotheta option. 

It happens while using 1 threads or several threads, and at various chromosomes or subset on samples). See the log below, please. 

I read that this issue appeared several times here.
Have you found a way to solve the problem ? What do you recommend to do?

Thanks a lot 
Claire

command line:
../../Softwares/angsd/angsd -P 3 -nQueueSize 50 -dosaf 1 -doThetas 1 -GL 1 -doMajorMinor 5 -ref ../genome/kelpfly_genome_AA_pacbio_100kb_plus.fasta -anc ../genome/kelpfly_genome_AA_pacbio_100kb_plus.fasta -fold 1 -remove_bads 1 -minMapQ 30 -minQ 20  -sites 01-GLsaf/ALL/sites_05.txt -pest 03-Thetas/AA.sfs -b Filelist/AAbam.filelist -out 03-Thetas/AA

log:
--> Printing at chr: 000176F|arrow pos:196690 chunknumber 1700 contains 4033 sites
/var/spool/slurm/slurmd/job33479/slurm_script: line 23: 51778 Segmentation fault      ../../Softwares/angsd/angsd -P 3 -nQueueSize 5$
        -> angsd version: 0.920 (htslib: 1.6) build(Mar 29 2018 20:30:16)

**Comment by eoziolor** [comment]
I've had this issue as well several times. I don't know if this is applicable here, but with help from our programmers I was able to run -doThetas without segmentation fault. I worked with our programmer core to figure out where the issue is and we came to the conclusion that the fault is thrown due to abcSaf.cpp and it is along these lines of code:

r->pLikes[myCounter] =new float[numInds+1];

#and the subsequent lines repeating the same code

When SFS is estimated from a folded allele frequency spectrum, for some reason the code iterates over numInds an inappropriate amount of times or it expects 2numInds+1. When those lines are changed to 2numInds+1 and the program is recompiled, it runs without segmentation fault. I am not sure if that changes the output significantly or not, but I know it fixes the -doThetas segfault for me.

**Comment by houzhe1991** [comment]
HI：
When I Calculate the thetas for each site through the command:

./angsd -bam bam.filelist -out out -doThetas 1 -doSaf 1 -pest out.sfs -anc chimpHg19.fa -GL 1
The output from the above command are 1 files out.thetas.gz ,
but have not the file out.thetas.idx .What happened? How can i get the idx file???

**Comment by clairemerot** [comment]
Thanks a lot to both of you for your answers.

@ANGSD Sorry it took me a while to work on that issue again. I have tried to replicate the problem on smaller sample size and funnily, it works well for 20 samples! I have tried with different subsets and I have the seg fault with other subsets of 48 or more samples. 
Would you like me to send the bam+ref & code so that you would be able to run tests on the 48 samples for instance ? By which way?

Then, I have tried eoziolor suggestion to edit the abcSaf.cpp and recompile. so far, it seems to have solved the problem of seg fault! Yet, I am not sure that the code is equivalent to what it is supposed to be? Could it affect the calculation of thetas to change 
"r->pLikes[myCounter] =new float[numInds+1];"
into "r->pLikes[myCounter] =new float[2*numInds+1];"  ?
Thanks

**Comment by ANGSD** [comment]
Should be solved in latest version.

Sorry for the delay, feel free to reopen if needed.

**Comment by pezhmansafdari** [comment]
Hi,

I am Having the same problem with all the new versions but, it works with version 0.910-7-g21a928a. The catch is the idx file is empty when it finishes. I have 5 samples only and this is the script that I am running:
/opt/angsd/angsd -bam bam.filelist -out out -doThetas 1 -doSaf 1 -pest out.sfs -anc snapdragon.fasta -GL 1
Is there a way to get the idx file from the thetas.gz file?

BR,
Pezhman
