### ISSUE TITLE
-doSaf only uses one variant from input .vcf

### ISSUE THREAD

**Issue by cursorially** [ANGSD/angsd#270]
Hi there,

I'm running -doSaf with a pre-pared [.vcf file](https://github.com/ANGSD/angsd/files/3829626/ancmiss10.info.vcf.gz) from GATK, each site having a PL field, with the following command:

`angsd -vcf-pl ancmiss10.info.vcf -doSaf 1 -out test -fai melanoplus.fasta.fai -anc melanoplus.fasta -nInd 7'

While the command executes fine and produces the outputs (excepting the same message as in #268 which doesn't seem to affect the running), it's only executing the calculation for the first variant listed in the attached file, such that I get the following messages in the console output:

`-> Total number of sites analyzed: 1`
`-> Number of sites retained after filtering: 1`

The input file contains 462 sites. Am I doing something wrong?

**Comment by martabe** [comment]
Hi,

I think I had the same problem; the vcfReader does not read past the first chromosome or contig.

I described it in [#258](https://github.com/ANGSD/angsd/issues/258#issuecomment-580623835) because I thought was still linked to the vcfReader issues with reading several chromosomes and mixing the coordinates at start and end of each chromosome.

Unfortunately I have no real solution so far. I found kind of a "workaround", but given that I am no expert and I am not sure of all the side effects of it, please **be extremely careful** if you decide to use it.
I found that if you remove the `break` statement on [line 308 of vcfReader.cpp](https://github.com/ANGSD/angsd/blob/66a5961fcbf3b691cf39f96f4bd90868efa002ea/vcfReader.cpp#L380) you can actually get all the chromosomes, but you will have duplicated lines in the output. You can easily remove duplicated lines later in bash though.

This is no real solution but I thought might be helpful to whom has skills to solve the problem.

Marta

**Comment by ANGSD** [comment]
So this should be resolved in this commit cea07b33567070d

**Comment by ANGSD** [comment]
Thanks for reporting it, and sorry for the delay. I dont have so much time to program as i used to have.
