### ISSUE TITLE
Including Invariant Sites

### ISSUE THREAD

**Issue by pstokespmb** [ANGSD/angsd#288]
Hi ANGSD team!

I am generating a VCF file for ~300 samples. I was able to do so, but I noticed the only sites that were called and present in the VCF file were sites that had at least one sample that was variant (which is to be expected).

I am also interested in calling invariant sites as well. It is just hard to tell if sites missing from the VCF file are invariant and not called or if there was no coverage for that site and that explains the missing calls. 

Is there a way to include invariant sites in addition to the variant sites in the VCF file?

The commands I used are below:

angsd -bam /global/scratch/peter_stokes/ncbi_fqs/unsorted_output/bamList_allSamples.txt \
-GL 2 -doGlf 2 \
-out /global/scratch/peter_stokes/angsdOutput/${outfile} \
-nThreads 12 -doMajorMinor 1 -SNP_pval 1e-6 \
-doMaf 1 -doGeno 32 -doPost 1 \
-minMapQ 30 -minQ 20 -minInd 1 -doDepth 1 \
-doCounts 1 -dumpCounts 2 -geno_minDepth -1 -geno_maxDepth 100 -postCutoff 0.95 \
-doIBS 2 -doCov 1 -doPlink 2 -doVcf 1 \
-dosmartcounts 1 \
-doHaploCall 2 -minMaf 0.05

**Comment by ANGSD** [comment]
Dear @pstokespmb Just remove the -minMaf 0.05 option and the -snp_pval 1e-6. Then the program should output all sites without any snpdiscovery. But please use the most recent version. and output bcf instead of vcf. The vcf output is deprecated. You can always convert the bcf to vcf with bcftools.

Best
