### ISSUE TITLE
Discrepancy angsd -doSaf1 screen output and saf output files

### ISSUE THREAD

**Issue by OKersten** [ANGSD/angsd#315]
Hi I am trying to generate saf files (and eventually a SFS) using angsd -doSaf 1 , followed by realSFS. 

These are the last few lines of screen output when I run angsd with -doSaf1:

>-> Printing at chr: Scaffolds_chromosome_4 pos:88569465 chunknumber 102000 contains 1043 sites
        -> Done reading data waiting for calculations to finish
        -> Done waiting for threads
        -> Output filenames:
                ->"MAI_Chromosome4.arg"
                ->"MAI_Chromosome4.saf.gz"
                ->"MAI_Chromosome4.saf.pos.gz"
                ->"MAI_Chromosome4.saf.idx"
        -> Tue May 19 15:20:30 2020
        -> Arguments and parameters for all analysis are located in .arg file
        -> Total number of sites analyzed: 81133859
        -> Number of sites retained after filtering: 1814160
        [ALL done] cpu-time used =  3931.35 sec
        [ALL done] walltime used =  4931.00 sec

However, when I run `realSFS print_header MAI_Chromosome4.saf.idx` the output is

> -> Version of fname:MAI_Chromosome4.saf.idx is:2
-> Assuming .saf.gz file: MAI_Chromosome4.saf.gz'
-> Assuming .saf.pos.gz: MAI_Chromosome4.saf.pos.gz
-> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:(null) chr:(null) start:-1 stop:-1 fstout:(null) oldout:0 seed:1589895626 bootstrap:0 resample_chr:0 whichFst:0 fold:0 ref:(null) anc:(null)
Information from index file: nChr:84 nSites:1814153
0	Scaffolds_chromosome_4	1814153	8	8`

Hence there is a discrepancy in the number of retained sites, i.e. sites used for the SFS. Strangely, this only occurs when the number of individuals in the bamlist of the -doSaf angsd run is large, i.e. no discrepancy when using 12 individuals, discrepancy using 42 individuals. 

Any ideas what could cause this behaviour?

Thanks for any help!

**Comment by ANGSD** [comment]
Sorry for the much delayed reply.

The  output from main angsd are all sites that are not discarded due to the upstream filters. The number of sites retained in the saf file are those sites which has not been removed by the upstream filters, and where the ancestral is defined. So in your case 7 sites should have an N in the ancestral. There could also be issues where the ancstral is not among the two most frequently observed alleles then these sites might also be removed due to lack of stability of the very low probability of the genotype likelihoods. I am closing this issue.
