### ISSUE TITLE
folded SFS generated from only variant sites gives wrong number of individuals

### ISSUE THREAD

**Issue by Jungal10** [ANGSD/angsd#321]
I have a bam file list of 24 individuals with which I have calculated its site allele frequency and then applied realSFS:

`~/angsd/angsd -out hybridus_ancRef \
-bam bams.file.list \
-doSaf 1 \
-GL 2 \
-doMaf 2 \
-doMajorMinor 5 \
-P 24 \
-anc Referencegenome.fa \
-remove_bads 1 \
-minMapQ 30 \
-minQ 20 \
-minInd 3 \
-SNP_pval 1e-6 \
-skipTriallelic	1
`

` ~/angsd/misc/realSFS step1.saf.idx  -P 4 -fold 1 > folded.sfs
`

I understand the reasoning on the folded SFS when invariant sites are present. The first and last "blocks" will be removed for plotting as they are non-segregating sites. But if the SAF output already excludes invariant sites, this will mean that realSFS is generating the wrong number of estimates. For instance, in this example, it should only generate 23 estimates but is calculating 25.
I am afraid that this will influence any further steps, as the theta's estimation since it uses the generated SFS as input.

Can you help me here?
Is this an error or is there any way of having realSFS to acknowledge that the SAF output already has only segregating sites?

Thank you

**Comment by ANGSD** [comment]
Hi just yesterday i pushed a new version of realSFS that should improve stability in the em optimization, so you might want to try that one.

As for your question.
If you have 5 diploid individuals you should have 11 categories of your frequency spectrum, since you have 0,1,2,...,10 chromosomes.
If you look at the folded then,
cat0 and cat 11 gets collapsed
cat1 and cat 10 gets collapsed
cat2 and cat 9 gets collapsed
cat3 and cat 8 gets collapsed
cat 4 and cat 7 gets collapsed
cat 5 and 6 gets collapsed.
So you should have 6 categories. The invariant is just the first one value.

So if you have 24 individuals you would expect to have 25 values in the folded.

**Comment by Jungal10** [comment]
Thank you for your very fast answer and explanation.
But if the `saf.idx file `is generated using `-SNP_pval 1e-6`, then there are no more invariant sites since this will be filtered out, correct?
So, how can then a category of invariant sites be present on the SFS?

This would mean that from 10 chromosomes, we only have estimates from 1 to 9. Since 0 and 10 will be non-segregating sites. And if these non-segregating sites were excluded by `-SNP p-value` filter, they should not be present on the realSFS estimates. 
from cat1 with the singletons until cat9 with 9 segregating sites.

**Comment by TeresaPegan** [comment]
Hi all,
This is happening to me as well. I built an SFS in ANGSD using the -sites argument, and my -sites file was generated with `-SNP_pval 1e-6`. I have 39 individuals and yet my resulting unfolded SFS has 77 elements, which is what I would expect when it _includes_ invariant sites. Furthermore, the entries corresponding to invariant sites are not 0, although they are rather low. But I expected them to be 0 because I thought I was only including variant sites in my SFS?
Is this just a result of ANGSD's probability framework -- the expected value for invariant sites in the SFS is non-zero due to uncertainty? The values are higher than I would have thought if that were the case, over 150 (out of ~16000 sites).

Here are a few more details:
A plot of my unfolded SFS. It has 77 elements.
![Screen Shot 2021-04-13 at 10 20 24 AM](https://user-images.githubusercontent.com/35701568/114568123-de38be00-9c41-11eb-84d5-80e148351159.png)

Here is a plot of the SFS after I folded it with ∂a∂i. I know that ∂a∂i masks the first and last entries in an SFS automatically and I got around this for the purposes of making this plot just by adding a 0 at the first and last position of the SFS. This SFS has 39 elements.
![image](https://user-images.githubusercontent.com/35701568/114568611-44254580-9c42-11eb-9a92-ed7241c42f65.png)

I also think it's pretty weird in both cases that the first four elements in the SFS have very low values? 

The sum of the SFS is 16828, which is one fewer than the number of sites in the SNP list I used as a -sites file when creating the SFS.


Thanks for any insights!
-Teresa

**Comment by TeresaPegan** [comment]
As a follow-up, I am wondering if the reason why the first 4 elements of my SFS show such low frequency is that sites with allele frequencies of only 1, 2, 3, etc are less likely to be confidently called SNPs by the `SNP_pval 1e-6` filter. If so, that seems like a pretty serious bias being introduced and a strong reason _not_ to build an SFS using only invariant sites.

**Comment by ANGSD** [comment]
Hi Teresa, the reason for the nonzero counts of the invariable bins are due to the probabilistic approach like you are suggesting.

The reason for the capped lower frequencies is due to the rather stringent 1e-6, you can relax this pvalue or you can run the analysis without snp calling which is also my recommended approach.

Best

**Comment by TeresaPegan** [comment]
Thanks so much for confirming that! I'll leave it up to you or the original author @Jungal10, but this topic could probably be closed now because you answered its main question (why some sites show up as invariant even when you use called SNPs).
