### ISSUE TITLE
Allele frequency estimation with -doMajorMinor 3

### ISSUE THREAD

**Issue by hzz0024** [ANGSD/angsd#342]
Hi there,

This is a simple question but I did not find the answer from the site. 

Using -doMajorMinor 3 and -site options allow me to calculate the allele frequencies using the predefined SNP list. I understand that these allele frequency values could be larger than 0.5. Just curious what allele frequencies are printed in the mafs file (at column knownEM), "minor allele" or "major allele"?  

Below is an example code I used for this purpose,

angsd -P 20 -doMaf 1 -dosaf 1 -GL 1 -doMajorMinor 3 \
      -anc anc.fa -remove_bads 1 -minMapQ 30 -minQ 20 -b bamlist.txt \
      -sites sites_all_maf0.05 -out pop1_output

Thanks!

HG

**Comment by z0on** [comment]
Hi HG - looks to me that you are specifying -anc, which would polarize your
SNPs: the alternative allele is going to be the one different from your
-anc genome, irrespective of whether it is major or minor. That’s the
allele which frequency you will see.

**Comment by hzz0024** [comment]
Hi, @z0on Thanks for the prompt reply. This is really helpful.

**Comment by hzz0024** [comment]
This is a following up question regarding the outputs with -doMaf, -doMajorMinor 3, and -sites options. I am asking this question because values in the mafs file are important for allele frequency change (i.e. delta_p) estimates.

Using the code above (see my first question) I obtained the allele frequency files (*mafs.gz) for each individual population. However, when I checked the allele frequency values, it only ranges from 0-0.85 but never exceed 0.9. Meanwhile, I saw 0 values, which indicate these alternative alleles are fixed. 

`# check the mean, maximum and minimum allele frequencies in an example maf file`
zcat REF_maf0.05_pctind0.7.mafs.gz | awk '{print $6}' | tail -n +2| awk '{if(min==""){min=max=$1}; if($1>max) {max=$1}; if($1<min) {min=$1}; total+=$1; count+=1} END {print total/count, max, min}'
`# mean, max, and min values`
0.176312 0.844308 0.000000

This happens in all my individual populations. I am wondering whether it is a technical issue or just a refection to the data itself? Or did I write something wrong with Angsd command? My Angsd version is **0.931**

Thanks,

HG

**Comment by DrLaurenCWhite** [comment]
Hello, I have a related question, I hope it's OK to post it here without making a new thread.

I am using -doMajorMinor 1 and -doMaf 1 without -anc, but specifying a reference file. In this instance, the allele frequencies under "knownEM" should always be the alternate allele? Regardless of whether it is the major or minor allele?
I ask as I seem to have a number of sites for which knownEM is <0.5, but for which the ref allele!=the major allele (from the major and ref columns of the maf output). Similarly for some sites for which knownEM is >0.5 the ref allele IS the major allele.  

I'd really appreciate any help you could give me in understanding this output! Below are an example of the output that is confusing me, and an example of my call to angsd. I am using ANGSD version 0.929

chromo pos major minor ref knownEM pK.EM nInd
chr1	195496035	G	C	G	0.904193	0	486
chr1	223110663	G	A	A	0.093694	0	489

angsd -b bamlist.txt -r chr1 -ref ref.fa -out outfile -GL 2 -doGlf 3 -doMajorMinor 1 -doMaf 1 -trim 0 -C 50 -minMapQ 20 -minQ 20 -uniqueOnly 1 -remove_bads 1 -SNP_pval 1e-6 -minInd 50 -minmaf 0.05

**Comment by DrLaurenCWhite** [comment]
Hi all, a quick update:
I have also found alleles with knownEM>0.5 when no reference is specified.
Cheers
-Lauren

**Comment by z0on** [comment]
I second Lauren’s question, I too get a handful of alleles with knownEM>0.5
when no reference is specified (the vast majority being <0.5)

**Comment by ANGSD** [comment]
Hi, im not sure which questions are still open in this thread. But here is some answers.

1) With -domajorminor 1. Then we infer the actual major and minor based on the genotype likelihoods.
2) Wtih -domajormnor 3. We are forcing the major and minor to be the two alleles from the -sites file.

With 2) the frequency can be >0.5 depending on the choice of alleles. For 1) I dont think this one can ever be above 0.5 but there might be borderline cases like triallelic sites where it could happen.

**Comment by nspope** [comment]
I'll add my 2c ...

There are two "estimation" steps here. The first is determining the major allele (doMajorMinor triggers this). AFAIK this simply tries to find the choice of major allele that maximizes the sum of genotype loglikelihoods across samples, assuming a uniform prior on genotypes. So it's trying to find the choice of bases "A" and "B" that maximize a likelihood of the form,
`\sum_i 0.25 * GL[AA]_i + 0.5 * GL[AB]_i + 0.25 * GL[BB]_i`
where the sum is over samples. This procedure doesn't assume that genotype frequencies follow HWE. If there's a lot of missing data, if the site is triallelic, or if the frequency is close to 0.5, then there may not be much information available in the data to determine the major.

The second step is to estimate the frequency conditional on the choice of major. Importantly, this assumes that genotype frequencies follow HWE: it maximizes a likelihood of the form
`\sum_i GL[AA]_i * freq^2 + 2 * GL[Aa]_i * freq * (1-freq) + GL[aa]_i * (1-freq)^2`
where the sum is over samples. Because this step assumes HWE, it's effectively fitting a different "model" than was used for the doMajorMinor step. If the choice of major allele was ambiguous in the doMajorMinor step, so that the assumption of HWE is influential, it is entirely possible that the estimated frequency may end up >0.5.

So, there's a different set of assumptions going into each step of this two-step process. Most of the time they line up, but sometimes they don't. The two steps could probably be combined into one, but that would be a bit of a mess with the way ANGSD is currently written (where doMajorMinor is used for a lot of things aside from estimating frequencies).

**Comment by nspope** [comment]
... ack, I mangled sums and products, but the edited response on the issue page is correct

**Comment by z0on** [comment]
very cool! thanks for the detailed explanation, Nate! it makes perfect sense.

**Comment by DrLaurenCWhite** [comment]
Thanks!

**Comment by ANGSD** [comment]
I am closing this issue.
