### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by jbruxaux** [ANGSD/angsd#344]
Hi!

I am currently trying to run angsd on a huge radseq dataset (2917 samples) with a very long and poorly assembled nuclear reference (23Gbp, 14 million contigs).
I managed to run angsd on the mitochondrial genome (one chromosome) so I'm rather confident my command line works properly, but it keeps crashing on the nuclear genome, no matter how I try to tune the parameters. Given the manual and this issue: https://github.com/ANGSD/angsd/issues/243 I tried to change the number of threads (from very high values like 28 threads, to 2 or 1), the minimum chunk size, to split the reference into 40 to 400 files, but I don't file a good solution...
I had initially angsd 0.921 installed on our cluster, I tried with a local installation of the most recent version (0.933-102-g7d57642).

My command line in case it helps:
`angsd -doCounts 1 -setMinDepth $gmin -setMaxDepth $gmax -setMaxDepthInd $maxdepthind -setMinDepthInd $mindepthind -minInd $minind -GL 1 -out $output/ANGSD_part0 -ref $ref -nThreads 2 -doGlf 2 -doMajorMinor 1 -SNP_pval 1e-6 -doMaf 1 -bam $bamlist  -minQ 20 -minMapQ 30 -minMaf 0.05 -uniqueOnly 1 -remove_bads 1 -baq 1 -skipTriallelic 1 -setMinChunkSize 250 -rf $refpart0 > $output/ANGSD_part0.out`

Thanks for your advice!

**Comment by ANGSD** [comment]
Sorry for the much delayed reply. To be honest this might not be the best scenario for angsd. For other users that try do do similar analyses my suggestion would be to run a separate angsd instance for each contig. When the filereading part of the code was written it was mainly optimized for long nice assembled chromosomes, so there are some bottlenecks associated with switch of chromosome or contig, and given the relative large number of samples it will take quite long.

There has been a number of fixes in the source since this issue was posted, so I am hopefull that the program would not crash. 

Again I am sorry my long response time. I am closing this issue. Feel free to reopen if still relevant or post a new issue if more suitable.

Best
