### ISSUE TITLE
chromosome names realSFS restrictions?

### ISSUE THREAD

**Issue by marqueda** [ANGSD/angsd#35]
Hi,

realSFS seems to allow only certain chromosome names, as I get the following error:
$ realSFS print ESCP.saf.idx
$        -> Version of fname:ESCP.saf.idx is:2
$ Problem with chr: chrX, key already exists

What are the restrictions to chromosome names (1...n, X, Y ?) and is there a workaround? The ref genome I am using is labelled with roman numbers.

Thank you very much for your help,
David

**Comment by ANGSD** [comment]
The naming doesnt matter but the order does matter, the chrs needs to be grouped together. Im assuming you are doing something with -rf and your rf files hasnt been sorted. I'll make a note on the wiki and in the code that they have to be sorted.

**Comment by marqueda** [comment]
Thank you for your quick help!
Best, David

**Comment by qinshengyuan** [comment]
Sorry, i still got the error as follow:  "Problem with chr: , key already exists, saffile needs to be sorted. (sort your -rf that you used for input)" 
what i should do now ... the order of my Chr is sorted in Chr1, Chr2....Chr3... 

Thank you 
Kobe QING

**Comment by sagitaninta** [comment]
I just wanna flag that I also still got this problem despite my .rf file being sorted already. This is the angsd version: 0.935 (htslib: 1.12) build(Mar 28 2021 01:00:43) installed by conda. I end up using -rf because after intending to use the -sites option, that always fail somehow, so that I used -rf and change the -sites file into an -rf file.

**Comment by janawold1** [comment]
Hello @sagitaninta, I'm having the exact same issue witht hte same program. Did you manage to sort this issue? This also appears to be an issue [here](https://github.com/ANGSD/angsd/issues/396). 

I'm getting a bit desperate to get this program to work at this point. I know it's not best practice, but to see if a number of unplaced scaffolds were causing issues due to variation in naming convention, I have realiged a subset of my samples to a reference with only the 'known' autosomes and repeated. Sadly this did not help in my case. Would anyone here happen to have any other clues or suggestions?

**Comment by ValentinavalenciaM** [comment]
hello, everyone I keep getting the same error: -> Version of fname:Ursus.autosomes.iberia.saf.idx is:2
Problem with chr: , key already exists, saffile needs to be sorted. (sort your -rf that you used for input) the analysis was performed with version 0.935 installed in conda. Any solution?

**Comment by ANGSD** [comment]
Please provide the commands you have been using.

**Comment by ValentinavalenciaM** [comment]
just to clarify the actual sfs file is in sge extension because that is the
extension required by the server queue system but the command function is :

realSFS Ursus.autosomes.iberia.saf.idx -fold 1

I include in addition the orders for previous orders corresponding to
genotyping (Genotyping.sh)

Thank you very much for your prompt response
