### ISSUE TITLE
Calculation of FST/PBS in populations with different sequence depth

### ISSUE THREAD

**Issue by hh622** [ANGSD/angsd#398]
Hello, 

I would like to use ANGSD/ngsTools to calculate Fst and then PBS/PBE at SNP level in maize populations. I have four test populations (Mexico high, Mexico low, South America High, South America Low) with sequence depth for each sample about 1X. However, I have another population used as an outgroup, which was sequenced about 30X. 

Questions:
1)do I need downsampling bam files of the outgroup population to about 1x for Fst/PBE calculation with ANGSD?
2)In the ngsTools/ANGSD tutorial (https://github.com/mfumagalli/ngsTools/blob/master/TUTORIAL.md), the PBS was calculated based on a sliding windows scan, I am wondering whether ANGSD can directly calculate PBS at SNP level? If so, how to modify the code?

Thanks,
Haixiao

**Comment by ANGSD** [comment]
Dear Haixaio,

1) No clearly not. You should not need to downsample anything. Just use the raw files, and maybe some extra filters if you want to.
2) It does not supply directly the fst or the pbs but it does the supply the terms that used to calculate these. 
http://www.popgen.dk/angsd/index.php/Fst#realSFS_fst_print

Hope this helps, otherwise write back.

**Comment by ANGSD** [comment]
I am closing this issue, feel free to reopen if needed.
