### ISSUE TITLE
doMaf gzipped output error

### ISSUE THREAD

**Issue by williampalmer** [ANGSD/angsd#4]
Hi there,

Attempting to use ANGSD for genotype calling, and using doMaf to see which sites to focus on. The output of doMaf is a gzipped file, but when I try to open it I get the error:

"gzip: sites.mafs.gz: invalid compressed data--crc error"

My command line is:
../angsd0.614/angsd -b bam.list -rf regions.txt -doMaf 1 -doMajorMinor 1 -snp_pval 0.01 -GL 2 -P 4 -baq 0 -minQ 13 -minMapQ 10 -out sites

I'm on Ubuntu 12.04, if that matters. I've tried redownloading and compiling with no effect. Is there any way to output the file not gzipped?

Cheers

**Comment by ANGSD** [comment]
Other users have experienced the same, and in all cases it was due to a problematic installation of zlib. angsd should report this when you try to run it. So I don’t think that is the case. But can you tell me which version of zlib you have installed?

You can make angsd report this by changing the if statement here:
https://github.com/ANGSD/angsd/blob/master/angsd.cpp#L177-L182

into if(1)


Thanks

**Comment by williampalmer** [comment]
I have 1.2.3 - I see now on the zlib website the newest version (zlib 1.2.8) fixes a bug that has to deal with decompression - could be what I'm experiencing? I will try reinstalling the newest version of zlib and see what happens. 
Thanks!

**Comment by williampalmer** [comment]
Updating to zlib 1.2.8 does the trick. Thanks for your help!
