### ISSUE TITLE
RealSFS replacing short scaffolds with sites from longer scaffolds

### ISSUE THREAD

**Issue by emilya21** [ANGSD/angsd#411]
Hi, I am trying to calculate pairwise Fst between two populations. 
 
I called SNPs between my populations and then calculated saf files for both populations based on those sites. 

Then I did the following:

realSFS pop1.saf.idx pop2.saf.idx -P 12 >pop1.pop2.ml

realSFS fst index pop1.saf.idx pop2.saf.idx -sfs pop1.pop2.ml -fstout pop1.pop2

realSFS fst stats pop1.pop2.fst.idx >> pop1_pop2_fst_results.txt

realSFS fst stats2 pop1.pop2.fst.idx -win 50000 -step 10000 > pop1.pop2.fst.window

This is all running without error, but the output is incorrect as any time the program encounters a scaffold/chr that the populations do not share any sites for, it assigns data from one of the longer scaffolds/chr to this scaffold. This is very concerning as I'm sure a lot of people are using this function, and it is very easy for this to go unnoticed in the results. 

I am using a recent build, "angsd version: 0.934 (htslib: 1.11) build(May 11 2021 19:16:02)"

I would appreciate any help in getting this fixed! Thank you!

Emily

**Comment by clairemerot** [comment]
Hello,
Yes this problem has been going on for some time. We observed the same in our data (see issue https://github.com/ANGSD/angsd/issues/200) and we end up avoiding using scaffolds below a certain size (by using wisely the -rf option). 
I was also doing a post-Fst analysis by verifying the size of the scaffolds in the file produced by "realSFS fst print". I excluded the ones that had a good name but wrong length (short scaffold for which realSFS was taking a longer one), and recalculated Fst on the corrected file. 
Good luck! And I hope this issue can be fixed indeed, it is not a problem for most people who have long chromosomes but it is if you work on non-model organisms with fragmented genomes.
Claire

**Comment by ANGSD** [comment]
Hi I cant replicate this from my test examples.
See below, please let me know if this issue is still relevant. 

./realSFS print p1.saf.idx 2>/dev/null
1	1	-0.100000	-0.100000	-0.100000	-inf	-inf	-inf	-inf
1	2	-inf	-0.200000	-0.200000	-0.200000	-inf	-inf	-inf
1	3	-inf	-inf	-0.300000	-0.300000	-0.300000	-inf	-inf
2	1	-0.110000	-0.110000	-0.100000	-inf	-inf	-inf	-inf
2	2	-inf	-0.220000	-0.220000	-0.200000	-inf	-inf	-inf
2	3	-inf	-inf	-0.330000	-0.330000	-0.330000	-inf	-inf
3	1	-0.111000	-0.111100	-0.111000	-inf	-inf	-inf	-inf
3	2	-inf	-0.222000	-0.222000	-0.222000	-inf	-inf	-inf
3	3	-inf	-inf	-0.333000	-0.333000	-0.333000	-inf	-inf
./realSFS print p2.saf.idx 2>/dev/null
1	1	-0.100000	-0.100000	-0.100000	-inf	-inf	-inf	-inf
1	2	-inf	-0.200000	-0.200000	-0.200000	-inf	-inf	-inf
1	3	-inf	-inf	-0.300000	-0.300000	-0.300000	-inf	-inf
3	1	-0.111000	-0.111100	-0.111000	-inf	-inf	-inf	-inf
3	3	-inf	-inf	-0.333000	-0.333000	-0.333000	-inf	-inf
[fvr124@compute09-snm-willerslev misc]$ cat sfs
6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 5.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 6.000000 
 ./realSFS fst index p1.saf.idx p2.saf.idx -sfs sfs -fstout asdf 2>/dev/null
 ./realSFS fst print asdf.fst.idx 2>/dev/null
1	1	0.016200	0.274633
1	2	0.000762	0.444444
1	3	-0.004383	0.501048
3	1	0.016201	0.274633
3	3	-0.004383	0.501048

**Comment by clairemerot** [comment]
I am sorry I haven't tried for a long time. It may have been fixed by updated versions of ANGSD or RealSFS? 
This was appearing in the fst by windows if I remember correctly
Thanks for checking!

**Comment by ANGSD** [comment]
Thanks for reporting this. And again I am sorry for the much delay in response time. It should be resolved in the most recent commit on github. I am closing this issue.
