### ISSUE TITLE
Masking regions in the genome

### ISSUE THREAD

**Issue by mlucenaperez** [ANGSD/angsd#47]
Hello there,

I have information about low complexity and repeated regions in my genome, and I would like to use it to increase accuracy in my analysis (SFS, theta calculus...). Removing the regions in all my BAMs might be problematic (time and space consuming). I tried to mask those regions in the -ref that I supplied, but I as far as I could understood that is not eliminating those regions for computing statistics. Thus, I was wondering if getting an SFS taking into account those regions, calculate Thetas and then ignore those positions for window analysis will have a major impact on my estimates.Any other solution? Recommendation? Sorry if this is not the forum to ask this question.

**Comment by ANGSD** [comment]
If it is just for the sfs based analysis, you can set the -anc to N for the sites you want to discard.
Otherwise use the -rf for defining all your region, or it is spread out across the genome use the -sites filer

http://www.popgen.dk/angsd/index.php/Filters <http://www.popgen.dk/angsd/index.php/Filters>

**Comment by ANGSD** [comment]
Ok, im closing this issue, feel free to reopen if needed

**Comment by nwales** [comment]
Hi, sorry for reopening this issue, but I too have questions on the functionality of the region file. In short, I would like to mask a number of inversions spread across a genome. I used the -rf approach with 345 regions to mask, and angsd tried to do a Region Lookup for 1035 segments (3X). I also saw that it repeated the analysis for a chromosome when multiple regions were on one chromosome (i.e. starting from scratch on a chromosome). Is this is the expected behavior? I had hope masking regions would speed up the analysis but that doesn't seem to be the case with this approach. Thanks! Nathan

**Comment by bishopia** [comment]
@nwales Did you ever find a solution to this? my region lookup value is also exactly 3x greater than the line count in the 1-base adjusted bedfile i'm trying to use as a region file. I wrote out a little more on at issue #447, before I realized you have asked a similar question.

**Comment by nwales** [comment]
@bishopia Actually, I didn't get much further on that analysis, so I can't offer too much more advice. I have continued to use the -sites function for when I want data overlapping with a SNP panel. But I've primarily used the -region method for limiting the analysis to one or two regions of interest. It could be fastest to produce a Beagle file for the whole genome and subsequently limit the output to the regions of interest--I don't know if there's a good tool for this or if you'd have to use a custom awk command.

**Comment by space-beaver** [comment]
> @bishopia Actually, I didn't get much further on that analysis, so I can't offer too much more advice. I have continued to use the -sites function for when I want data overlapping with a SNP panel. But I've primarily used the -region method for limiting the analysis to one or two regions of interest. It could be fastest to produce a Beagle file for the whole genome and subsequently limit the output to the regions of interest--I don't know if there's a good tool for this or if you'd have to use a custom awk command.

Hi @nwales and @bishopia, 

I'm trying to calculate safs and folded spectra from whole genome data, excluding region 1700000 - 1800000 on chr16 of my data (this is a highly SNP dense region that is affecting stats). I'm not sure how to code for this correctly and wondered if either of you could advise. TIA
