### ISSUE TITLE
Error in calculating allele frequency

### ISSUE THREAD

**Issue by qianqianqian0717** [ANGSD/angsd#473]
Hi,
I used the following command to convert the BAM file of ancestral chromosome and reference genome into FA format and found that the number of chromosomes would decrease

angsd -i Laolan.sort.markdup.bam -only_proper_pairs 1 -uniqueOnly 1 -remove_bads 1 -nThreads 6 -minQ 20 -minMapQ 30 -doFasta 2 -basesPerline 100 -doCounts 1 -out Golan

which would result in an error when the number of ancestral chromosomes is not the same as the number of chromosomes in the rest of BAM file when calculating allele frequency

![image](https://user-images.githubusercontent.com/92802020/161748814-48e82eea-001e-4ca1-b555-32f0fd665e0b.png)

How can I solve it? Looking forward to your answer.

**Comment by ANGSD** [comment]
Dear @qianqianqian0717 , the software complains that your chromosomename 'NW_008326844.1' does not exist, but I am abit puzzled by the error message because that would indicate that you are also trying to load a fastafile? Which does not seem to be the case from your supplied command line. I am closing this issue, but feel free to reopen in case I misunderstood.

Best
