### ISSUE TITLE
allele frequencies for haploids -doHaploCall 2 and -domaf1

### ISSUE THREAD

**Issue by gLaRob** [ANGSD/angsd#481]
Hi,

Thank you for building such a wonderful program.
My question pertains to allele frequencies from haploid individuals. I am interested in invariant sites for homozygous/hemizygous individuals, thus I have not been providing a snp_pval filter. Below is the flags I am running.

angsd -gl 1 - Scaffold -P 10 -doHaploCall 2 -doMajorMinor 1 -doCounts 1 -doMaf 1 \
-minMapQ 20 -minQ 20 -remove_bads 1 \
-bam bamlist.txt
-minInd 5 -setMinDepth 1 

My question pertains to the information being outputted by doMaf 1 in respects to haploids. 1) Is it accurate to say if a locus is invariant in haploids, domaf will still infer a minor? 3) Is knownEM of a value such as, 0.000004, indicative of fixed for major? The minor should never have a known EM of 1 in haploids, correct?

2) Does this hold true in invariant sites for diploids?

-doHaploCall 
chr     pos     major   ind0    ind1    ind2    ind3    ind4    ind5    ind6    ind7    ind8
Scaffold      1    A       N       N       A       A       A       N       A       A       N

-domaf 1 results
chromo  position        major   minor   knownEM nInd
Scaffold      1    A       C       0.000004        5

Many thanks,
German

**Comment by ANGSD** [comment]
Dear @gLaRob , most methods in ANGSD are assuming diploid individuals. We recently added support for sfs estimation from haploids but standard -domaf is assuming diploid and hwe so for haploids these are not meaningful.
The haplocall does pseudohaploid genotype calling so that should be fine.

Hope this helps, I will close the issue. Sorry for delayed response.
