### ISSUE TITLE
-dobcf --ignore-RG flag

### ISSUE THREAD

**Issue by Sol2Man** [ANGSD/angsd#517]
Hello,

I was attempting to -dovcf as written here (http://popgen.dk/angsd/index.php/Vcf), but this appears to have been deprecated. I am attempting to make a bcf now so I can pipe this file into beagle 4.1 but I am getting the following warning. While I could simply follow what this states, I wanted more information on the `--ignore-RG` which I can't seem to find documentation for.

```
Please add the following parameters:
-gl 1 -dopost 1 -domajorminor 1 -domaf 1 -dobcf 1 --ignore-RG 0 -dogeno 1 -docounts 1
```

Best wishes,
Sol

**Comment by ANGSD** [comment]
Dear @Sol2Man 

The ignore-RG 0 option means that the sampleid name of individuals in the analysis will be populated by the SM tag given by the readgroup information in the header, otherwise the sampleids will be inferred by the filename.

The software currently does not merge reads from different bam files even if they have the same SM tag.


Best regards
