### ISSUE TITLE
memory consumption of realSFS

### ISSUE THREAD

**Issue by biozzq** [ANGSD/angsd#69]
Hi @ANGSD 

I was running `realSFS` on 98 genomes with 1.6GB sites, but I found it will consume too much memory (about 1T). I hope a way I can reduce the memory usage and still get a proper result about the summary statistics.

Best
Zhuqing

**Comment by ANGSD** [comment]
To get a global estimate of the sfs, you will need to load the entire dataset.
But you can select limit the number of sites being loaded into memory using the -nSites argument.

Hopefully this helps.

**Comment by biozzq** [comment]
Hi @ANGSD 

Thanks, I realized that I can reduce memory usage using the `-nSites` argument, but the results are different from running with entire dataset. Like following,

Run with entire dataset
`1514348010.160848 3040309.629727 1799474.986311 1201972.790719 863945.395953 657560.924589 525223.506178 432321.668769 367909.174327 326483.116935 292509.120957 273645.670553 262914.989037 262964.354174 273038.461740 297879.032027 348469.902682 449523.287427 30795608.827044`
Run with setting -nSites 1000000000
`972819557.287878 1964605.147031 1148055.839643 766092.739752 552052.537582 419649.209583 335623.777568 276047.386973 234276.138329 206706.109067 184620.200535 174060.103137 167027.152693 167966.392818 172714.965139 188365.273247 220295.993825 286915.783564 19715367.961638
541528491.976446 1075632.687634 651476.212087 435857.005527 311888.690260 237880.127496 189686.977030 156182.262888 133698.478641 119729.471824 107896.645958 99625.933734 95845.297831 95024.557679 100304.058532 109520.250211 128185.275382 162601.129091 11080237.961749`

How can I get the finally SFS when I run with `-nSites`, can I just sum the expected number in the same entry?

Best
Zhuqing

**Comment by ANGSD** [comment]
it should be ok just to do sum of the per entry values. But i would make
sure that they look somewhat similar.

Your two examples can't be merged because they dont have the same number of
entries.

echo "972819557.287878 1964605.147031 1148055.839643 766092.739752
552052.537582 419649.209583 335623.777568 276047.386973 234276.138329
206706.109067 184620.200535 174060.103137 167027.152693 167966.392818
172714.965139 188365.273247 220295.993825 286915.783564 19715367.961638
541528491.976446 1075632.687634 651476.212087 435857.005527 311888.690260
237880.127496 189686.977030 156182.262888 133698.478641 119729.471824
107896.645958 99625.933734 95845.297831 95024.557679 100304.058532
109520.250211 128185.275382 162601.129091 11080237.961749"|wc

       1      38     542

echo "1514348010.160848 3040309.629727 1799474.986311 1201972.790719
863945.395953 657560.924589 525223.506178 432321.668769 367909.174327
326483.116935 292509.120957 273645.670553 262914.989037 262964.354174
273038.461740 297879.032027 348469.902682 449523.287427 30795608.827044" |wc

       1      19     275

**Comment by biozzq** [comment]
Hi @ANGSD 

When I running with `-nSites`, the result is two lines which can not be accepted by `angsd`. You can see above example, the total number of sites is about 1.6Gb, when running without  the `-nSites` argument, the SFS file contains a single line. But when running with `-nSites 1000000000`, the SFS file contains two lines which come from two different blocks. So I want to do sum in order to get a result which is similarity with running with entire dataset. I hope to do sum of the entries from different blocks will be ok.

Best
Zhuqing

**Comment by ANGSD** [comment]
ahh yes, sure. Each line is an estimate of the sfs for a region with
-nSites number of sites. So I would just take the sum of the columns, but
also check that they looked somewhat similar.

**Comment by biozzq** [comment]
Thanks for your help.
Best
Zhuqing
