### ISSUE TITLE
beginner question for speeding up analyses with angsd

### ISSUE THREAD

**Issue by guillaume-dumont** [ANGSD/angsd#94]
Hi,

I am very new in ANGSD and so my question is probably a bit stupid but I don't manage to find the answer by myself.
If in a command I use, for example, the argument -doMAF and I want to use an other command which also need this argument doMAF, can I use the output of the 1st command or do I need to run both command with the argument anyway? 
Concretely, if I ran this command : 
angsd -bam $bam.list -ref $ref -out $outputfile -doCounts 1 -doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 -doGlf 2
and then I want to run this one :
angsd -bam $bam.list -ref $ref -out $outputfile -doCounts 1 -doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 -doGeno 32 -doPost 1
can I simply run : 
angsd -bam $bam.list -ref $ref -out $outputfile -doGeno 32 -doPost 1
to speed up the calculation time or it is not possible ?
Or if I knew before I will need these two command, I guess I could have run :
angsd -bam $bam.list -ref $ref -out $outputfile -doCounts 1 -doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 -doGlf 2 -doGeno 32 -doPost 1
to win a bit of time ?

Thanks by advance,
Guillaume

**Comment by ANGSD** [comment]
Sure you should be able to mix commands. You can start with but you need to
add all arguments.

If you want -doPost 1, then you require an estimator for the frequency
which could be -domaf 1, but -domaf 1 requires that you have inferred
majorminor, so you would add -domajorminor 1. And then you also need to
pick which genotype likelihood model you want, so that could be -gl 1. In
general the program should complain if there are some requirements.

Let me know how it goes. If you have a fast diskio system you can also take
advantage of multiple analysis threads -P 4. But this will only make sense
if what you are doing is computational intensive.

Best

**Comment by guillaume-dumont** [comment]
Hi, 

Thank you for your fast answer! Actually I had already run the 1st command and the 2nd is running know (both with -gl indeed, everything seems fine so far). And so, if I understand correctly, there is no way to use outputs of the 1st in the 2nd and so it's smarter to predict a bit what you want to do to mix the commands and win time.

Thanks again !
Guillaume

**Comment by ANGSD** [comment]
Hello Guillaume. Glad i could help. Let me us know if you have other
questions. Ill close this issue then.

Best
