### ISSUE TITLE
Limit of file number/file size?

### ISSUE THREAD

**Issue by joaneel** [ANGSD/angsd#98]
Hi there,
I am running angsd to calculate genotype probabilities from bam files.
Here is my command:

$PATH/angsd -P 1 -b bam.list -out out_all  -GL 2 -ref $REF -doMajorMinor 4 -doMaf 1 -skipTriallelic 1 -SNP_pval 1e-3 -doGeno 32 -doPost 1 -minQ 20 -minMapQ 20 -minInd 15 -doCounts 1 -setMinDepthInd 5 -setMaxDepthInd 500

Is there a number (and size) of files beyond which the program won't be able to execute the command?

When the  bam.list file contains 666 files, the program crashes (no error message, just "killed"). When bam.list has a subset of 100 files from the original list, the command is completed without problem.

Any idea why this happens? 
The server I am using server is not set up with an open file size limit, which is why I think it could be a program-related problem.

Best

Joane

**Comment by ANGSD** [comment]
Hello Joane, sorry for my delayed response I've been preoccupied.

Un linux and OS X you can see how many files you are allowed to open with the ulimit -n command
On my mac is is 256 files on a linux server im using once in a while it is 1024 files.
But everything counts with this limit, so it is not just the number of bam/cram files. It would also by your -ref file along with the bai/crai files if these have been indexed. So I would make sure you have a nice buffer.

Hopefully this helps

Best

**Comment by joaneel** [comment]
Hi Matteo,
Thank you for your reply.
It seems that the number of files allowed to be open is pretty large already on my system (>100,000).
Here is the output of the full ulimit -a command, in case something there strikes you as being a potential problem:
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 966280
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 122880
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 20480
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

Best

Joane

**Comment by ANGSD** [comment]
Hello Joane Im closing this issue. Feel free to reopen if needed.

**Comment by xinxin2** [comment]
Hi
Recently, I also encountered the same problem as above. When calling SNP of 75 samples with angsd software, they always said that they were killed, but 50 samples could run normally. When I type the command ulimit-n at the terminal, the result is 1024. I thought it was a memory problem, so I tried to turn off all the files. Only one terminal was opened to process 100 samples. The others were not opened, but they were still killed. But the result is that it exceeds the killing position when 75 samples were run before, because multiple terminals were opened when running 75 samples. Generally speaking, when I use the angsd software call SNP, as long as more than a certain number of samples will be killed, but I have a large number, and I have to call SNP at the same time to get what I need. How can I solve this situation?
Best

Xinxin

**Comment by xinxin2** [comment]
@joaneel Hello! I'd like to ask if the problem in front of you has been solved later. Could you tell me how to solve your problem? Thank you very much!

**Comment by joaneel** [comment]
Hi Xinxin,
Sorry that was years and years ago, I don' t work in genetics anymore and
don' t have access to the code anymore.
I hope you find your answer.
Best
Joane

**Comment by xinxin2** [comment]
OK，thank you！Best wishes!



---Original---
